### ISSUE TITLE
missing .json file HBN QSIprep dataset

### ISSUE THREAD

**Issue by PeerHerholz** [PeerHerholz/bids_bep16_conv#1]
Hi @arokem,

I just added a small function to download the [QSIprep-processed HBN data from OSF](https://osf.io/bz2vj/). However, given the `current state` outlined in [PR 24](https://github.com/bids-standard/bids-bep016/pull/24/files) the respective `.json` would be missing. For now, I only included the data of `sub-NDAREK918EC2` (based on the QC scores). 

Could you maybe have a look/provide some pointers re the `json` file? I looked on S3 but didn't find the fitting one and was thus wondering if this is due to my lack of knowledge or if it's actually not there.

It would be great to hear from you re this.

Cheers, Peer

**Comment by arokem** [comment]
No, you're correct that qsiprep did not produce the json files, but I think that it would be rather straightforward to generate the json in this case, based on the instructions [here](https://bids-specification.readthedocs.io/en/stable/05-derivatives/02-common-data-types.html): 

```

{
    "Sources": ["bids:raw:sub-NDAREK918EC2/ses-HBNsiteSI/dwi/sub-NDAREK918EC2_ses-HBNsiteSI_acq-64dir_dwi.nii.gz",
                "bids:raw:sub-NDAREK918EC2/ses-HBNsiteSI/dwi/sub-NDAREK918EC2_ses-HBNsiteSI_acq-64dir_dwi.bval",
                "bids:raw:sub-NDAREK918EC2/ses-HBNsiteSI/dwi/sub-NDAREK918EC2_ses-HBNsiteSI_acq-64dir_dwi.bvec",
                "bids:raw:sub-NDAREK918EC2/ses-HBNsiteSI/anat/sub-NDAREK918EC2_ses-HBNsiteSI_T1w.nii.gz",
                "bids:raw:sub-NDAREK918EC2/ses-HBNsiteSI/fmap/sub-NDAREK918EC2_ses-HBNsiteSI_magnitude1.nii.gz",
                "bids:raw:sub-NDAREK918EC2/ses-HBNsiteSI/fmap/sub-NDAREK918EC2_ses-HBNsiteSI_magnitude2.nii.gz",
                "bids:raw:sub-NDAREK918EC2/ses-HBNsiteSI/fmap/sub-NDAREK918EC2_ses-HBNsiteSI_phasediff.nii.gz"
], 
    "SpatialReference": "bids:raw:sub-NDAREK918EC2/ses-HBNsiteSI/anat/sub-NDAREK918EC2_ses-HBNsiteSI_T1w.nii.gz"
}

```

In addition to propagating the original metadata that are in the json for the raw data files that are [here](https://fcp-indi.s3.amazonaws.com/index.html#data/Projects/HBN/BIDS_curated/sub-NDAREK918EC2/ses-HBNsiteSI/dwi/)

**Comment by PeerHerholz** [comment]
Hi Ariel,

thank you very much for your message and helpful information.

Just to be sure: I would need to create the `json` via two steps:

- get the `metadata` from the corresponding `raw data` files
- add the information re `sources` and `SpatialReference` you provided

However, shouldn't there also be pipeline-related information? Sorry, I haven't work with that type of `derivative` yet.

Thanks again, best, Peer

**Comment by arokem** [comment]
Yes. I think that's all correct.

I think that you can use the dataset_description file [here](https://fcp-indi.s3.amazonaws.com/data/Projects/HBN/BIDS_curated/derivatives/qsiprep/dataset_description.json) for the pipeline information.

**Comment by arokem** [comment]
Yes. I think that's all correct.

I think that you can use the dataset_description file [here](
https://fcp-indi.s3.amazonaws.com/data/Projects/HBN/BIDS_curated/derivatives/qsiprep/dataset_description.json)
for the pipeline information.
