### ISSUE TITLE
Download brainmask from qsiprep derivatives

### ISSUE THREAD

**Issue by arokem** [PeerHerholz/bids_bep16_conv#9]
The HBN dataset has brainmasks already computed. Many software will take brainmasks as input to make the computation shorter.

**Comment by PeerHerholz** [comment]
Thx @arokem, fixed via [this commit](https://github.com/PeerHerholz/bids_bep16_conv/commit/40115797b4dd521d6c3465c8feceed6c76ab176b).

**Comment by arokem** [comment]
I think this one? 329e04bf901bdbf653dab2234fa2ea4466e0ea66
